image: Visual Studio 2017
build_script:
  - sed s/1.0.0/$(appveyor_build_version)/g JacobsApps.CleanArchitectureProjectTemplate.CSharp.nuspec
  - nuget restore src/CleanArchitectureTemplate.sln
  - nuget pack JacobsApps.CleanArchitectureProjectTemplate.CSharp.nuspec
  