image: Visual Studio 2017
configuration: Release
platform: Any CPU

init:
- ps: $env:customnugetversion = if ($env:APPVEYOR_REPO_BRANCH  -eq "master") { "$env:APPVEYOR_BUILD_VERSION" } else { "$env:APPVEYOR_BUILD_VERSION-beta" }
- ps: Update-AppveyorBuild -Version $env:customnugetversion
- echo %customnugetversion%

build_script:
  - sed s/1.0.0/%customnugetversion%/g JacobsApps.CleanArchitectureProjectTemplate.CSharp.nuspec
  - nuget restore src/CleanArchitectureTemplate.sln
  - nuget pack JacobsApps.CleanArchitectureProjectTemplate.CSharp.nuspec -version %customnugetversion%
  