image: Visual Studio 2017
configuration: Release
platform: Any CPU

build_script:  
  - nuget restore src/CleanArchitectureTemplate.sln
  - dotnet build src/CleanArchitectureTemplate.sln
  - dotnet test src/CleanArchitectureTemplate.sln
  - nuget pack JacobsApps.CleanArchitectureProjectTemplate.CSharp.nuspec
 
artifacts:
- path: '**\*.nupkg'

deploy:
    provider: NuGet
    on:
      branch: master      
    api_key:
        secure: 5ZzlyVXW9Ch/50cNaTw5Q7I+g2uJ9THFy3c9K+XmgQWN3SPoXqxkPHSX1KIj/P4l
        skip_symbols: false
  