trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '*' 
    exclude:
    - 'README.md'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
   
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud-CleanArchitectureTemplate'
    organization: 'jacobduijzer-github'
    scannerMode: 'CLI'
    configMode: 'file'

- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: 'build'
    projects: 'src/CleanArchitectureTemplate.sln'
    arguments: '/p:DefineConstants=IncludeSampleCode'

- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: 'test'
    projects: 'src/CleanArchitectureTemplate.sln'
    arguments: '/p:DefineConstants=IncludeSampleCode /p:CollectCoverage=true /p:CoverletOutputFormat=opencover'

- task: SonarCloudAnalyze@1

- task: NuGetToolInstaller@1
  displayName: "Install latest nuget"
  inputs:
    versionSpec: '>= 5.4.0-0'

- task: NuGetCommand@2
  displayName: "NuGet Pack"
  inputs:
    command: 'custom'
    arguments: 'pack JacobsApps.CleanArchitectureProjectTemplate.CSharp.nuspec -NoDefaultExcludes'

# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(Build.SourcesDirectory)'
#     Contents: 'JacobsApps.CleanArchitectureProjectTemplate.CSharp.*.nupkg'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'

- task: NuGetCommand@2
  displayName: "NuGet Push"
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.SourcesDirectory)/JacobsApps.CleanArchitectureProjectTemplate.CSharp.*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'