trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '*' 
    exclude:
    - 'README.md'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
   
- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: 'build'
    projects: 'src/CleanArchitectureTemplate.sln'
- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: 'test'
    projects: 'src/CleanArchitectureTemplate.sln'

- task: NuGetCommand@2
  displayName: "Pack"
  inputs:
    command: 'pack'
    packagesToPack: 'JacobsApps.CleanArchitectureProjectTemplate.CSharp.nuspec'
    versioningScheme: 'off'

- task: NuGetCommand@2
  displayName: "Push"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'